const CONFIG = {
    titleWeb: "Hé Lu",
    introTitle: 'MinhDue',
    introDesc: `bạn êuuu`,
    btnIntro: '^^HiHi^^',
    title: 'say bạn từ lúc mới wen 🥰',
    desc: 'bạn làm mình quay cuồng trong cơn mer ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'yêu Bùi Xuân Chuyên :))',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'đợi lớn mình đưa bạn đi chơiii.',
    btnAccept: 'okeee <3',
