const CONFIG = {
    titleWeb: "Hé lu",
    introTitle: 'minhdue',
    introDesc: `iu bạn quá tr`,
    btnIntro: '^^HiHi^^',
    title: 'umebanwatr 🥰',
    desc: 'babe đừng làm anh suyyyy ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại yêu mình <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'yêu bùi xuân chuyên ạ',
    mess: 'Mình biết mà 🥰. Yêu bạn nhiều nhiều 😘😘',
    messDesc: 'đợi mình lớn mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
